<?php

namespace AppBundle\Repository\PriceList;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailRepository extends \Doctrine\ORM\EntityRepository
{
}
