<?php

namespace AppBundle\Repository\PriceList;

/**
 * PriceListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function delete($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:PriceListItem p WHERE p.id = :id;'
            )
            ->execute(['id'=> $id]);
    }
}
